const languages = {
  languages: [
    { lang: 'English', code: 'en', ui: 'EN', flag: 'images/flags/gb.svg' },
    { lang: 'Afrikaans', code: 'af', ui: 'AF', flag: 'images/flags/za.svg' },
    { lang: 'Albanian', code: 'sq', ui: 'SQ', flag: 'images/flags/al.svg' },
    { lang: 'Amharic', code: 'am', ui: 'AM', flag: 'images/flags/et.svg' },
    { lang: 'Arabic', code: 'ar', ui: 'AR', flag: 'images/flags/sa.svg' },
    { lang: 'Armenian', code: 'hy', ui: 'HY', flag: 'images/flags/am.svg' },
    { lang: 'Azerbaijani', code: 'az', ui: 'AZ', flag: 'images/flags/az.svg' },
    { lang: 'Basque', code: 'eu', ui: 'EU', flag: 'images/flags/es.svg' },
    { lang: 'Belarusian', code: 'be', ui: 'BE', flag: 'images/flags/by.svg' },
    { lang: 'Bengali', code: 'bn', ui: 'BN', flag: 'images/flags/bd.svg' },
    { lang: 'Bosnian', code: 'bs', ui: 'BS', flag: 'images/flags/ba.svg' },
    { lang: 'Bulgarian', code: 'bg', ui: 'BG', flag: 'images/flags/bg.svg' },
    { lang: 'Catalan', code: 'ca', ui: 'CA', flag: 'images/flags/es.svg' },
    { lang: 'Chinese', code: 'zh', ui: 'ZH', flag: 'images/flags/cn.svg' },
    { lang: 'Corsican', code: 'co', ui: 'CO', flag: 'images/flags/fr.svg' },
    { lang: 'Croatian', code: 'hr', ui: 'HR', flag: 'images/flags/hr.svg' },
    { lang: 'Czech', code: 'cs', ui: 'CS', flag: 'images/flags/cz.svg' },
    { lang: 'Danish', code: 'da', ui: 'DA', flag: 'images/flags/dk.svg' },
    { lang: 'Dutch', code: 'nl', ui: 'NL', flag: 'images/flags/nl.svg' },
    { lang: 'Esperanto', code: 'eo', ui: 'EO', flag: 'images/flags/eu.svg' }, // якщо нема — заміниш/видалиш
    { lang: 'Estonian', code: 'et', ui: 'ET', flag: 'images/flags/ee.svg' },
    { lang: 'Finnish', code: 'fi', ui: 'FI', flag: 'images/flags/fi.svg' },
    { lang: 'French', code: 'fr', ui: 'FR', flag: 'images/flags/fr.svg' },
    { lang: 'Frisian', code: 'fy', ui: 'FY', flag: 'images/flags/nl.svg' },
    { lang: 'Galician', code: 'gl', ui: 'GL', flag: 'images/flags/es.svg' },
    { lang: 'Georgian', code: 'ka', ui: 'KA', flag: 'images/flags/ge.svg' },
    { lang: 'German', code: 'de', ui: 'DE', flag: 'images/flags/de.svg' },
    { lang: 'Greek', code: 'el', ui: 'EL', flag: 'images/flags/gr.svg' },
    { lang: 'Gujarati', code: 'gu', ui: 'GU', flag: 'images/flags/in.svg' },
    {
      lang: 'Haitian Creole',
      code: 'ht',
      ui: 'HT',
      flag: 'images/flags/ht.svg',
    },
    { lang: 'Hausa', code: 'ha', ui: 'HA', flag: 'images/flags/ng.svg' },
    { lang: 'Hebrew', code: 'he', ui: 'HE', flag: 'images/flags/il.svg' },
    { lang: 'Hindi', code: 'hi', ui: 'HI', flag: 'images/flags/in.svg' },
    { lang: 'Hungarian', code: 'hu', ui: 'HU', flag: 'images/flags/hu.svg' },
    { lang: 'Icelandic', code: 'is', ui: 'IS', flag: 'images/flags/is.svg' },
    { lang: 'Igbo', code: 'ig', ui: 'IG', flag: 'images/flags/ng.svg' },
    { lang: 'Indonesian', code: 'id', ui: 'ID', flag: 'images/flags/id.svg' },
    { lang: 'Irish', code: 'ga', ui: 'GA', flag: 'images/flags/ie.svg' },
    { lang: 'Italian', code: 'it', ui: 'IT', flag: 'images/flags/it.svg' },
    { lang: 'Japanese', code: 'ja', ui: 'JA', flag: 'images/flags/jp.svg' },
    { lang: 'Javanese', code: 'jv', ui: 'JV', flag: 'images/flags/id.svg' },
    { lang: 'Kannada', code: 'kn', ui: 'KN', flag: 'images/flags/in.svg' },
    { lang: 'Kazakh', code: 'kk', ui: 'KK', flag: 'images/flags/kz.svg' },
    { lang: 'Khmer', code: 'km', ui: 'KM', flag: 'images/flags/kh.svg' },
    { lang: 'Kinyarwanda', code: 'rw', ui: 'RW', flag: 'images/flags/rw.svg' },
    { lang: 'Korean', code: 'ko', ui: 'KO', flag: 'images/flags/kr.svg' },
    { lang: 'Kurdish', code: 'ku', ui: 'KU', flag: 'images/flags/iq.svg' },
    { lang: 'Kyrgyz', code: 'ky', ui: 'KY', flag: 'images/flags/kg.svg' },
    { lang: 'Lao', code: 'lo', ui: 'LO', flag: 'images/flags/la.svg' },
    { lang: 'Latin', code: 'la', ui: 'LA', flag: 'images/flags/va.svg' },
    { lang: 'Latvian', code: 'lv', ui: 'LV', flag: 'images/flags/lv.svg' },
    { lang: 'Lithuanian', code: 'lt', ui: 'LT', flag: 'images/flags/lt.svg' },
    {
      lang: 'Luxembourgish',
      code: 'lb',
      ui: 'LB',
      flag: 'images/flags/lu.svg',
    },
    { lang: 'Macedonian', code: 'mk', ui: 'MK', flag: 'images/flags/mk.svg' },
    { lang: 'Malagasy', code: 'mg', ui: 'MG', flag: 'images/flags/mg.svg' },
    { lang: 'Malay', code: 'ms', ui: 'MS', flag: 'images/flags/my.svg' },
    { lang: 'Malayalam', code: 'ml', ui: 'ML', flag: 'images/flags/in.svg' },
    { lang: 'Maltese', code: 'mt', ui: 'MT', flag: 'images/flags/mt.svg' },
    { lang: 'Maori', code: 'mi', ui: 'MI', flag: 'images/flags/nz.svg' },
    { lang: 'Marathi', code: 'mr', ui: 'MR', flag: 'images/flags/in.svg' },
    { lang: 'Mongolian', code: 'mn', ui: 'MN', flag: 'images/flags/mn.svg' },
    { lang: 'Myanmar', code: 'my', ui: 'MY', flag: 'images/flags/mm.svg' },
    { lang: 'Nepali', code: 'ne', ui: 'NE', flag: 'images/flags/np.svg' },
    { lang: 'Norwegian', code: 'no', ui: 'NO', flag: 'images/flags/no.svg' },
    {
      lang: 'Nyanja (Chichewa)',
      code: 'ny',
      ui: 'NY',
      flag: 'images/flags/mw.svg',
    },
    { lang: 'Odia(Oriya)', code: 'or', ui: 'OR', flag: 'images/flags/in.svg' },
    { lang: 'Pashto', code: 'ps', ui: 'PS', flag: 'images/flags/af.svg' },
    { lang: 'Persian', code: 'fa', ui: 'FA', flag: 'images/flags/ir.svg' },
    { lang: 'Polish', code: 'pl', ui: 'PL', flag: 'images/flags/pl.svg' },
    {
      lang: 'Portuguese(Portugal, Brazil)',
      code: 'pt',
      ui: 'PT',
      flag: 'images/flags/pt.svg',
    },
    { lang: 'Punjabi', code: 'pa', ui: 'PA', flag: 'images/flags/in.svg' },
    { lang: 'Romanian', code: 'ro', ui: 'RO', flag: 'images/flags/ro.svg' },
    { lang: 'Russian', code: 'ru', ui: 'RU', flag: 'images/flags/ru.svg' },
    { lang: 'Samoan', code: 'sm', ui: 'SM', flag: 'images/flags/ws.svg' },
    { lang: 'Scots Gaelic', code: 'gd', ui: 'GD', flag: 'images/flags/gb.svg' },
    { lang: 'Serbian', code: 'sr', ui: 'SR', flag: 'images/flags/rs.svg' },
    { lang: 'Sesotho', code: 'st', ui: 'ST', flag: 'images/flags/ls.svg' },
    { lang: 'Shona', code: 'sn', ui: 'SN', flag: 'images/flags/zw.svg' },
    { lang: 'Sindhi', code: 'sd', ui: 'SD', flag: 'images/flags/pk.svg' },
    {
      lang: 'Sinhala(Sinhalese)',
      code: 'si',
      ui: 'SI',
      flag: 'images/flags/lk.svg',
    },
    { lang: 'Slovak', code: 'sk', ui: 'SK', flag: 'images/flags/sk.svg' },
    { lang: 'Slovenian', code: 'sl', ui: 'SL', flag: 'images/flags/si.svg' },
    { lang: 'Somali', code: 'so', ui: 'SO', flag: 'images/flags/so.svg' },
    { lang: 'Spanish', code: 'es', ui: 'ES', flag: 'images/flags/es.svg' },
    { lang: 'Sundanese', code: 'su', ui: 'SU', flag: 'images/flags/id.svg' },
    { lang: 'Swahili', code: 'sw', ui: 'SW', flag: 'images/flags/tz.svg' },
    { lang: 'Swedish', code: 'sv', ui: 'SV', flag: 'images/flags/se.svg' },
    {
      lang: 'Tagalog(Filipino)',
      code: 'tl',
      ui: 'TL',
      flag: 'images/flags/ph.svg',
    },
    { lang: 'Tajik', code: 'tg', ui: 'TG', flag: 'images/flags/tj.svg' },
    { lang: 'Tamil', code: 'ta', ui: 'TA', flag: 'images/flags/in.svg' },
    { lang: 'Tatar', code: 'tt', ui: 'TT', flag: 'images/flags/ru.svg' },
    { lang: 'Telugu', code: 'te', ui: 'TE', flag: 'images/flags/in.svg' },
    { lang: 'Thai', code: 'th', ui: 'TH', flag: 'images/flags/th.svg' },
    { lang: 'Turkish', code: 'tr', ui: 'TR', flag: 'images/flags/tr.svg' },
    { lang: 'Turkmen', code: 'tk', ui: 'TK', flag: 'images/flags/tm.svg' },
    { lang: 'Ukrainian', code: 'uk', ui: 'UA', flag: 'images/flags/ua.svg' },
    { lang: 'Urdu', code: 'ur', ui: 'UR', flag: 'images/flags/pk.svg' },
    { lang: 'Uyghur', code: 'ug', ui: 'UG', flag: 'images/flags/cn.svg' },
    { lang: 'Uzbek', code: 'uz', ui: 'UZ', flag: 'images/flags/uz.svg' },
    { lang: 'Vietnamese', code: 'vi', ui: 'VI', flag: 'images/flags/vn.svg' },
    { lang: 'Welsh', code: 'cy', ui: 'CY', flag: 'images/flags/gb.svg' },
    { lang: 'Xhosa', code: 'xh', ui: 'XH', flag: 'images/flags/za.svg' },
    { lang: 'Yiddish', code: 'yi', ui: 'YI', flag: 'images/flags/il.svg' },
    { lang: 'Yoruba', code: 'yo', ui: 'YO', flag: 'images/flags/ng.svg' },
    { lang: 'Zulu', code: 'zu', ui: 'ZU', flag: 'images/flags/za.svg' },
  ],
}

export default languages
